//! # Grids — the Mutable Instruments topographic drum sequencer
//!
//! Ported from pichenettes/eurorack (grids/pattern_generator.cc, MIT,
//! copyright 2011 Emilie Gillet, attribution preserved): the 5×5 drum
//! map with bilinear interpolation between nodes (the 25 node tables
//! extracted verbatim to grids_nodes.bin), per-part randomness
//! perturbation, density thresholds, accents above 192, and the
//! euclidean mode's Bjorklund table generated by the same algorithm
//! as resources/lookup_tables.py.
//!
//! In los grids is a NOTE SOURCE: it follows the transport (8 steps
//! per beat, 32-step patterns) and emits kick/snare/hat note events
//! on `grids/N/bd·sd·hh` — bind a peaks channel or any voice to them.
//! The three trigger levels and the accent also publish on the
//! modulation bus.

use std::io;
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};

use anyhow::Result;
use crossterm::{
    event::{self, EnableMouseCapture, Event, KeyCode, KeyModifiers, MouseEventKind},
    execute,
    terminal::{enable_raw_mode, EnterAlternateScreen},
};
use ratatui::{
    backend::CrosstermBackend,
    style::Style,
    text::{Line, Span},
    widgets::{Block, Borders, Paragraph},
    Terminal,
};

use crate::routing::{self, SourceAddr};
use crate::shm::{AudioEvent, EventRingbuf, Manifest, ModulationBus, ShmTransport};
use crate::state;

/// Note-source band: 160 + instance*3 + {bd, sd, hh} (branches owns
/// 200+; the sequencer band ends far below).
pub const NOTE_SOURCE_BASE: u8 = 160;
pub const STEPS_PER_PATTERN: u32 = 32;
const NUM_PARTS: usize = 3;

/// The 25 drum-map nodes, 3 instruments × 32 steps each, extracted
/// from grids/resources.cc.
static NODES: &[u8] = include_bytes!("grids_nodes.bin");

/// drum_map\[i\]\[j\] node indices (pattern_generator.cc).
const DRUM_MAP: [[usize; 5]; 5] = [
    [10, 8, 0, 9, 11],
    [15, 7, 13, 12, 6],
    [18, 14, 4, 5, 3],
    [23, 16, 21, 1, 2],
    [24, 19, 17, 20, 22],
];

#[inline]
fn node_byte(node: usize, instrument: usize, step: usize) -> u8 {
    NODES[node * 96 + instrument * 32 + step]
}

#[inline]
fn u8_mix(a: u8, b: u8, balance: u8) -> u8 {
    ((a as u16 * (255 - balance as u16) + b as u16 * balance as u16) >> 8) as u8
}

/// pattern_generator.cc ReadDrumMap: bilinear interpolation between
/// the four surrounding nodes.
pub fn read_drum_map(step: usize, instrument: usize, x: u8, y: u8) -> u8 {
    // upstream: i = x>>6 is the FIRST index into drum_map
    let i = (x >> 6) as usize;
    let j = (y >> 6) as usize;
    let a = node_byte(DRUM_MAP[i.min(4)][j.min(4)], instrument, step);
    let b = node_byte(DRUM_MAP[(i + 1).min(4)][j.min(4)], instrument, step);
    let c = node_byte(DRUM_MAP[i.min(4)][(j + 1).min(4)], instrument, step);
    let d = node_byte(DRUM_MAP[(i + 1).min(4)][(j + 1).min(4)], instrument, step);
    u8_mix(u8_mix(a, b, x << 2), u8_mix(c, d, x << 2), y << 2)
}

/// The Bjorklund euclidean table, generated exactly like
/// resources/lookup_tables.py (length 1–32 × density 0–31 bitmasks).
pub fn build_euclidean() -> Vec<u32> {
    fn pattern(k: usize, n: usize) -> Vec<u8> {
        if k == 0 || n == 0 {
            return vec![0; n];
        }
        let mut groups: Vec<Vec<u8>> = (0..n)
            .map(|i| if i < k { vec![1] } else { vec![0] })
            .collect();
        let mut k = k;
        while k > 1 && groups.len() > k {
            let cut = k.min(groups.len() - k);
            let tail: Vec<Vec<u8>> = groups.split_off(groups.len() - cut);
            for (g, t) in groups.iter_mut().zip(tail) {
                g.extend(t);
            }
            k = cut;
        }
        groups.into_iter().flatten().collect()
    }
    let mut table = Vec::with_capacity(32 * 32);
    for num_steps in 1..=32_usize {
        for d in 0..32_usize {
            let num_notes = ((d as f64 / 31.0 * num_steps as f64).round()) as usize;
            let bits = pattern(num_notes.min(num_steps), num_steps);
            let mut mask = 0u32;
            for (i, b) in bits.iter().enumerate() {
                if *b != 0 {
                    mask |= 1 << i;
                }
            }
            table.push(mask);
        }
    }
    table
}

/// One evaluation step's output.
#[derive(Debug, Clone, Copy, Default)]
pub struct StepTriggers {
    pub fired: [bool; NUM_PARTS],
    pub accent: [bool; NUM_PARTS],
}

/// The pattern core (drums + euclidean modes), firmware-exact.
pub struct PatternCore {
    pub drums_mode: bool,
    pub x: u8,
    pub y: u8,
    pub randomness: u8,
    pub density: [u8; NUM_PARTS],
    pub euclidean_length: [u8; NUM_PARTS],
    part_perturbation: [u8; NUM_PARTS],
    euclidean_step: [usize; NUM_PARTS],
    euclidean: Vec<u32>,
    rng: u32,
}

impl PatternCore {
    pub fn new(seed: u32) -> Self {
        PatternCore {
            drums_mode: true,
            x: 128,
            y: 128,
            randomness: 0,
            density: [128; NUM_PARTS],
            euclidean_length: [255; NUM_PARTS],
            part_perturbation: [0; NUM_PARTS],
            euclidean_step: [0; NUM_PARTS],
            euclidean: build_euclidean(),
            rng: seed.max(1),
        }
    }

    fn random_byte(&mut self) -> u8 {
        self.rng = self.rng.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        (self.rng >> 24) as u8
    }

    pub fn reset(&mut self) {
        self.euclidean_step = [0; NUM_PARTS];
    }

    /// Evaluate one 32nd-of-a-bar step.
    pub fn step(&mut self, step: usize) -> StepTriggers {
        let mut out = StepTriggers::default();
        if self.drums_mode {
            if step == 0 {
                for i in 0..NUM_PARTS {
                    let r = self.randomness >> 2;
                    let byte = self.random_byte();
                    self.part_perturbation[i] = ((byte as u16 * r as u16) >> 8) as u8;
                }
            }
            for i in 0..NUM_PARTS {
                let mut level = read_drum_map(step, i, self.x, self.y);
                level = level.saturating_add(self.part_perturbation[i]);
                let threshold = !self.density[i];
                if level > threshold {
                    out.fired[i] = true;
                    out.accent[i] = level > 192;
                }
            }
        } else {
            // euclidean refreshes on sixteenths (even steps)
            if step & 1 == 1 {
                return out;
            }
            for i in 0..NUM_PARTS {
                let length = ((self.euclidean_length[i] >> 3) + 1) as usize;
                let density = (self.density[i] >> 3) as usize;
                let address = (length - 1) * 32 + density;
                while self.euclidean_step[i] >= length {
                    self.euclidean_step[i] -= length;
                }
                let mask = 1u32 << self.euclidean_step[i] as u32;
                if self.euclidean[address] & mask != 0 {
                    out.fired[i] = true;
                    out.accent[i] = self.euclidean_step[i] == 0;
                }
                self.euclidean_step[i] += 1;
            }
        }
        out
    }
}

// ── module shell ───────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Row {
    Mode,
    X,
    Y,
    Chaos,
    Fill1,
    Fill2,
    Fill3,
    Len1,
    Len2,
    Len3,
}

const ROWS: [Row; 10] = [
    Row::Mode,
    Row::X,
    Row::Y,
    Row::Chaos,
    Row::Fill1,
    Row::Fill2,
    Row::Fill3,
    Row::Len1,
    Row::Len2,
    Row::Len3,
];

/// CV bank — every value row takes a cable (mode is the selector).
const BINDABLE: [Row; 9] = [
    Row::X,
    Row::Y,
    Row::Chaos,
    Row::Fill1,
    Row::Fill2,
    Row::Fill3,
    Row::Len1,
    Row::Len2,
    Row::Len3,
];
const N_SRC: usize = BINDABLE.len();

struct GridsState {
    drums_mode: bool,
    x: f32,
    y: f32,
    chaos: f32,
    fill: [f32; 3],
    len: [f32; 3],
    srcs: [Option<SourceAddr>; N_SRC],
    resolved: [Option<usize>; N_SRC],
    eff: [f32; N_SRC],
    fired_now: [bool; 3],
    selected: usize,
}

impl GridsState {
    fn new() -> Self {
        let mut s = GridsState {
            drums_mode: true,
            x: 0.5,
            y: 0.5,
            chaos: 0.0,
            fill: [0.5; 3],
            len: [1.0; 3],
            srcs: Default::default(),
            resolved: Default::default(),
            eff: [0.0; N_SRC],
            fired_now: [false; 3],
            selected: 0,
        };
        for (k, r) in BINDABLE.iter().enumerate() {
            s.eff[k] = s.get(*r);
        }
        s
    }

    fn get(&self, r: Row) -> f32 {
        match r {
            Row::X => self.x,
            Row::Y => self.y,
            Row::Chaos => self.chaos,
            Row::Fill1 => self.fill[0],
            Row::Fill2 => self.fill[1],
            Row::Fill3 => self.fill[2],
            Row::Len1 => self.len[0],
            Row::Len2 => self.len[1],
            Row::Len3 => self.len[2],
            Row::Mode => 0.0,
        }
    }

    fn set(&mut self, r: Row, v: f32) {
        let v = v.clamp(0.0, 1.0);
        match r {
            Row::X => self.x = v,
            Row::Y => self.y = v,
            Row::Chaos => self.chaos = v,
            Row::Fill1 => self.fill[0] = v,
            Row::Fill2 => self.fill[1] = v,
            Row::Fill3 => self.fill[2] = v,
            Row::Len1 => self.len[0] = v,
            Row::Len2 => self.len[1] = v,
            Row::Len3 => self.len[2] = v,
            Row::Mode => {}
        }
    }
}

const SRC_SLOT_BASE: usize = 50;

impl crate::undo::ParamUndo for GridsState {
    fn get_param(&self, slot: usize) -> Option<crate::undo::ParamValue> {
        use crate::undo::ParamValue as V;
        if let Some(i) = slot.checked_sub(SRC_SLOT_BASE) {
            if i < N_SRC {
                return Some(V::Src(self.srcs[i].as_ref().map(|a| a.to_string())));
            }
            return None;
        }
        let r = *ROWS.get(slot)?;
        Some(match r {
            Row::Mode => V::Bool(self.drums_mode),
            _ => V::F32(self.get(r)),
        })
    }

    fn set_param(&mut self, slot: usize, value: crate::undo::ParamValue) {
        use crate::undo::ParamValue as V;
        let parse = |v: &Option<String>| v.as_deref().and_then(SourceAddr::parse);
        if let Some(i) = slot.checked_sub(SRC_SLOT_BASE) {
            if i < N_SRC {
                if let V::Src(v) = &value {
                    self.srcs[i] = parse(v);
                    self.resolved[i] = None;
                }
            }
            return;
        }
        match (ROWS.get(slot).copied(), value) {
            (Some(Row::Mode), V::Bool(v)) => self.drums_mode = v,
            (Some(r), V::F32(v)) => self.set(r, v),
            _ => {}
        }
    }
}

fn snapshot_params(s: &GridsState) -> state::GridsParams {
    let src = |i: usize| s.srcs[i].as_ref().map(|a| a.to_string());
    state::GridsParams {
        format: state::STATE_FORMAT,
        mode: Some(if s.drums_mode { "drums" } else { "euclid" }.into()),
        x: Some(s.x),
        y: Some(s.y),
        chaos: Some(s.chaos),
        fill1: Some(s.fill[0]),
        fill2: Some(s.fill[1]),
        fill3: Some(s.fill[2]),
        len1: Some(s.len[0]),
        len2: Some(s.len[1]),
        len3: Some(s.len[2]),
        x_src: src(0),
        y_src: src(1),
        chaos_src: src(2),
        fill1_src: src(3),
        fill2_src: src(4),
        fill3_src: src(5),
        len1_src: src(6),
        len2_src: src(7),
        len3_src: src(8),
    }
}

fn apply_params(s: &mut GridsState, p: &state::GridsParams) {
    if let Some(m) = p.mode.as_deref() {
        s.drums_mode = m != "euclid";
    }
    macro_rules! f {
        ($row:expr, $field:ident) => {
            if let Some(v) = p.$field {
                s.set($row, v);
            }
        };
    }
    f!(Row::X, x);
    f!(Row::Y, y);
    f!(Row::Chaos, chaos);
    f!(Row::Fill1, fill1);
    f!(Row::Fill2, fill2);
    f!(Row::Fill3, fill3);
    f!(Row::Len1, len1);
    f!(Row::Len2, len2);
    f!(Row::Len3, len3);
    let parse = |o: &Option<String>| o.as_deref().and_then(SourceAddr::parse);
    s.srcs = [
        parse(&p.x_src),
        parse(&p.y_src),
        parse(&p.chaos_src),
        parse(&p.fill1_src),
        parse(&p.fill2_src),
        parse(&p.fill3_src),
        parse(&p.len1_src),
        parse(&p.len2_src),
        parse(&p.len3_src),
    ];
    s.resolved = Default::default();
}

// ── engine thread ──────────────────────────────────────────────────────────

/// MIDI pitches the three parts emit (kick/snare/hat homes).
const PART_NOTES: [f32; 3] = [36.0, 38.0, 42.0];

fn engine_thread(shared: Arc<Mutex<GridsState>>, instance: usize) -> Result<()> {
    let mut manifest = Manifest::open().or_else(|_| Manifest::create())?;
    // four claims: bd/sd/hh trigger levels + accent on the bus
    manifest.register("grids", instance, None, 4)?;
    let mod_base = manifest.claimed_base();
    let mut modbus = ModulationBus::open()
        .or_else(|_| ModulationBus::create())
        .ok();
    let mut producer = EventRingbuf::open_producer().ok();
    let transport = ShmTransport::open().ok();

    let base = NOTE_SOURCE_BASE.saturating_add((instance as u8) * 3);
    let mut core = PatternCore::new(0x9a1d_5000 ^ instance as u32);
    let mut last_step: Option<u32> = None;
    let mut gate_off_at: [Option<u64>; 3] = [None; 3];
    let mut gate_level = [0.0_f32; 3];
    let mut accent_level = 0.0_f32;
    let mut ticks: u64 = 0;

    loop {
        if ticks.is_multiple_of(64) {
            if producer.is_none() {
                producer = EventRingbuf::open_producer().ok();
            }
            let entries = manifest.entries();
            let mut s = shared.lock().unwrap();
            for k in 0..N_SRC {
                s.resolved[k] = s.srcs[k]
                    .as_ref()
                    .and_then(|a| routing::resolve(&entries, a));
            }
            let mask = s
                .resolved
                .iter()
                .flatten()
                .filter(|&&c| c < 64)
                .fold(0u64, |m, &c| m | (1 << c));
            manifest.publish_consumes(mask, 0);
        }

        let (drums_mode, x, y, chaos, fill, len) = {
            let mut s = shared.lock().unwrap();
            let bus = modbus.as_ref();
            // max/min, not clamp: NaN from a stale channel dies here
            #[allow(clippy::manual_clamp)]
            let cv = |k: usize, manual: f32, s: &GridsState| -> f32 {
                match (s.resolved[k], bus) {
                    (Some(ch), Some(b)) => b.get(ch).max(0.0).min(1.0),
                    _ => manual,
                }
            };
            let mut vals = [0.0_f32; N_SRC];
            for (k, r) in BINDABLE.iter().enumerate() {
                vals[k] = cv(k, s.get(*r), &s);
                s.eff[k] = vals[k];
            }
            (
                s.drums_mode,
                vals[0],
                vals[1],
                vals[2],
                [vals[3], vals[4], vals[5]],
                [vals[6], vals[7], vals[8]],
            )
        };

        if let Some(ref t) = transport {
            let playing = t.playing();
            let clock = t.clock();
            let bpm = f64::from(t.bpm()).clamp(20.0, 300.0);
            let sr = f64::from(t.sample_rate()).max(1.0);
            // grids: 8 steps per beat
            let samples_per_step = (60.0 / bpm * sr / 8.0).max(1.0);
            let step_index = ((clock as f64 / samples_per_step) as u64
                % STEPS_PER_PATTERN as u64) as u32;

            if playing && last_step != Some(step_index) {
                last_step = Some(step_index);
                if step_index == 0 {
                    core.reset();
                }
                core.drums_mode = drums_mode;
                core.x = (x * 255.0) as u8;
                core.y = (y * 255.0) as u8;
                core.randomness = (chaos * 255.0) as u8;
                for i in 0..3 {
                    core.density[i] = (fill[i] * 255.0) as u8;
                    core.euclidean_length[i] = (len[i] * 255.0) as u8;
                }
                let trig = core.step(step_index as usize);
                let mut any_accent = false;
                for i in 0..3 {
                    if trig.fired[i] {
                        let velocity = if trig.accent[i] { 127 } else { 100 };
                        any_accent |= trig.accent[i];
                        let hz = 440.0 * 2.0_f32.powf((PART_NOTES[i] - 69.0) / 12.0);
                        if let Some(ref mut pr) = producer {
                            let _ = pr.write_event(&AudioEvent::note_on_hz(
                                hz,
                                velocity,
                                base + i as u8,
                                clock as u32,
                            ));
                        }
                        gate_level[i] = if trig.accent[i] { 1.0 } else { 0.8 };
                        // gate off halfway to the next step
                        gate_off_at[i] =
                            Some(clock.wrapping_add((samples_per_step / 2.0) as u64));
                    }
                }
                accent_level = if any_accent { 1.0 } else { 0.0 };
                let mut s = shared.lock().unwrap();
                s.fired_now = trig.fired;
            }
            for i in 0..3 {
                if let Some(off_at) = gate_off_at[i] {
                    if clock >= off_at {
                        if let Some(ref mut pr) = producer {
                            let _ = pr.write_event(&AudioEvent::note_off_source(
                                0,
                                base + i as u8,
                                clock as u32,
                            ));
                        }
                        gate_level[i] = 0.0;
                        gate_off_at[i] = None;
                        if i == 0 {
                            accent_level = 0.0;
                        }
                    }
                }
            }
            if !playing {
                last_step = None;
            }
        }

        if let (Some(b), Some(bus)) = (mod_base, modbus.as_mut()) {
            for (i, g) in gate_level.iter().enumerate() {
                bus.set(b + i, *g);
            }
            bus.set(b + 3, accent_level);
        }

        ticks += 1;
        thread::sleep(Duration::from_millis(1));
    }
}

// ── ui ─────────────────────────────────────────────────────────────────────

fn row_label(r: Row) -> &'static str {
    match r {
        Row::Mode => "mode",
        Row::X => "map x",
        Row::Y => "map y",
        Row::Chaos => "chaos",
        Row::Fill1 => "fill bd",
        Row::Fill2 => "fill sd",
        Row::Fill3 => "fill hh",
        Row::Len1 => "len bd",
        Row::Len2 => "len sd",
        Row::Len3 => "len hh",
    }
}

fn src_index(r: Row) -> Option<usize> {
    BINDABLE.iter().position(|b| *b == r)
}

fn binding_slot(r: Row) -> Option<usize> {
    src_index(r).map(|i| SRC_SLOT_BASE + i)
}

fn row_text(s: &GridsState, r: Row) -> String {
    match r {
        Row::Mode => if s.drums_mode { "drums (the map)" } else { "euclid" }.into(),
        Row::Len1 | Row::Len2 | Row::Len3 => {
            let v = s.get(r);
            format!("{} steps", ((v * 255.0) as u8 >> 3) + 1)
        }
        _ => format!("{:.0}%", s.get(r) * 100.0),
    }
}

#[allow(clippy::too_many_arguments)]
fn draw_ui(
    terminal: &mut Terminal<CrosstermBackend<io::Stdout>>,
    s: &GridsState,
    instance: usize,
    show_help: bool,
    overlay: Option<&str>,
    picker: Option<(Vec<String>, usize)>,
    entries: &[crate::shm::ManifestEntry],
) -> Result<()> {
    use crate::theme;
    terminal.draw(|f| {
        let area = f.area();
        let w = area.width as usize;
        let h = area.height as usize;
        let mut lines: Vec<Line> = Vec::new();
        lines.push(theme::header(
            "GRIDS",
            &format!("topographic {}", instance),
            "",
            w,
        ));
        let mut spans = vec![Span::styled("  ".to_string(), theme::chrome())];
        for (name, fired) in ["bd", "sd", "hh"].iter().zip(s.fired_now.iter()) {
            spans.push(Span::styled(
                format!("{name} "),
                if *fired { theme::value() } else { theme::dim() },
            ));
        }
        lines.push(Line::from(spans));
        lines.push(Line::from(""));

        let bar_w = theme::bar_width(w, 32);
        for (i, r) in ROWS.iter().enumerate() {
            let selected = i == s.selected;
            let label_style = if selected {
                theme::selected()
            } else {
                theme::chrome()
            };
            let mut spans: Vec<Span> =
                vec![Span::styled(format!(" {:<8}", row_label(*r)), label_style)];
            let bound = src_index(*r).is_some_and(|k| s.srcs[k].is_some());
            let hue = src_index(*r)
                .and_then(|k| s.srcs[k].as_ref())
                .map(|a| routing::cable_color(entries, a));
            if src_index(*r).is_some() {
                let shown = match src_index(*r) {
                    Some(k) if s.srcs[k].is_some() => s.eff[k],
                    _ => s.get(*r),
                };
                spans.extend(theme::bar(shown, None, bar_w, hue.unwrap_or_else(theme::cv)));
            } else {
                spans.push(Span::styled(" ".repeat(bar_w), theme::dim()));
            }
            let vstyle = if selected {
                theme::selected()
            } else if let Some(hu) = hue {
                theme::signal(hu)
            } else {
                theme::value()
            };
            let mark = if bound { theme::BIND } else { ' ' };
            spans.push(Span::styled(
                format!(" {}{}", mark, row_text(s, *r)),
                vstyle,
            ));
            lines.push(Line::from(spans));
        }

        theme::anchor_bottom(&mut lines, h, 2);
        lines.push(theme::rule(w));
        lines.push(theme::status("NORMAL", overlay.unwrap_or(""), "", w));
        f.render_widget(Paragraph::new(lines), area);

        if show_help {
            let help = Paragraph::new(vec![
                Line::from("━━━ GRIDS · topographic drums (Mutable Instruments port) ━━━"),
                Line::from(""),
                Line::from("  mode      drums (the 5×5 map) | euclid"),
                Line::from("  map x/y   where on the map of beats you are"),
                Line::from("  chaos     per-pattern randomness"),
                Line::from("  fill      density per part (bd/sd/hh)"),
                Line::from("  len       euclid pattern lengths"),
                Line::from(""),
                Line::from("Follows the transport: 8 steps per beat, 32-step"),
                Line::from("patterns. Emits notes on grids/N/bd·sd·hh — bind a"),
                Line::from("peaks channel (or anything) to them. Triggers +"),
                Line::from("accent also publish on the bus."),
                Line::from(""),
                Line::from("  ? closes help"),
            ])
            .style(Style::default().fg(theme::ink()).bg(theme::bg()))
            .block(
                Block::default()
                    .borders(Borders::ALL)
                    .border_style(theme::chrome())
                    .title(Span::styled(" GRIDS ", theme::chrome_hi())),
            );
            f.render_widget(help, area);
        }

        if let Some((rows, sel)) = picker {
            let ph = (rows.len() as u16 + 2).min(area.height);
            let pw = rows.iter().map(|r| r.len()).max().unwrap_or(10).max(20) as u16 + 4;
            let rect = ratatui::layout::Rect::new(
                (area.width.saturating_sub(pw)) / 2,
                (area.height.saturating_sub(ph)) / 2,
                pw.min(area.width),
                ph,
            );
            f.render_widget(ratatui::widgets::Clear, rect);
            let items: Vec<ratatui::widgets::ListItem> = rows
                .iter()
                .enumerate()
                .map(|(i, row)| {
                    let style = if i == sel {
                        theme::selected()
                    } else {
                        theme::value()
                    };
                    ratatui::widgets::ListItem::new(row.clone()).style(style)
                })
                .collect();
            let list = ratatui::widgets::List::new(items).block(
                Block::default()
                    .borders(Borders::ALL)
                    .border_style(theme::chrome())
                    .title(Span::styled(" bind ", theme::chrome_hi())),
            );
            f.render_widget(list, rect);
        }
    })?;
    Ok(())
}

pub fn run(instance: usize) -> Result<()> {
    state::setup_save_signal();
    state::setup_reload_signal();
    state::write_pid_file("grids", instance);

    let shared = Arc::new(Mutex::new(GridsState::new()));
    if let Ok(p) = state::load_module_state::<state::GridsParams>("grids", instance) {
        apply_params(&mut shared.lock().unwrap(), &p);
    }

    let engine_state = Arc::clone(&shared);
    let builder = thread::Builder::new().name(String::from("grids-engine"));
    let _ = builder.spawn(move || {
        // black box: a dead engine thread must leave a trace
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            engine_thread(engine_state, instance)
        }));
        let msg = match result {
            Ok(Ok(())) => return,
            Ok(Err(e)) => format!("error: {e}"),
            Err(p) => format!(
                "PANIC: {}",
                p.downcast_ref::<&str>()
                    .map(|s| s.to_string())
                    .or_else(|| p.downcast_ref::<String>().cloned())
                    .unwrap_or_else(|| "<non-string payload>".into())
            ),
        };
        eprintln!("[grids {instance}] engine thread died: {msg}");
        let path = crate::state::tmp_dir().join(format!("grids_{instance}.crash"));
        let _ = std::fs::write(path, &msg);
    });

    for attempt in 0..20 {
        match enable_raw_mode() {
            Ok(()) => break,
            Err(e) if attempt < 19 => {
                let _ = e;
                thread::sleep(Duration::from_millis(200));
            }
            Err(e) => return Err(anyhow::anyhow!("enabling raw mode: {}", e)),
        }
    }
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen, EnableMouseCapture)?;
    let mut terminal = Terminal::new(CrosstermBackend::new(stdout))?;

    let mut show_help = false;
    let mut count = crate::keys::Count::default();
    let mut pending_g = false;
    let mut history = crate::undo::ParamHistory::default();
    let mut ex = crate::excmd::ExLine::default();
    let mut picker = crate::picker::Picker::default();
    let mut ex_msg: Option<String> = None;
    let mut patch_name: Option<String> = None;
    let mut should_quit = false;
    let mut transport_ui: Option<ShmTransport> = ShmTransport::open().ok();
    let manifest = Manifest::open().or_else(|_| Manifest::create())?;
    let mut ui_entries: Vec<crate::shm::ManifestEntry> = Vec::new();
    let mut ui_entries_at: Option<Instant> = None;
    let mut baseline =
        state::to_toml_string(&snapshot_params(&shared.lock().unwrap())).unwrap_or_default();

    loop {
        if state::check_save_signal() {
            let params = snapshot_params(&shared.lock().unwrap());
            let _ = state::save_module_state("grids", instance, &params);
        }
        if state::check_reload_signal() {
            if let Ok(p) = state::load_module_state::<state::GridsParams>("grids", instance) {
                apply_params(&mut shared.lock().unwrap(), &p);
            }
        }
        if ui_entries_at.is_none_or(|t| t.elapsed() > Duration::from_secs(1)) {
            ui_entries = manifest.entries();
            ui_entries_at = Some(Instant::now());
        }

        let overlay = if ex.is_active() {
            Some(ex.display())
        } else {
            ex_msg.clone()
        };
        {
            let s = shared.lock().unwrap();
            let picker_rows = picker.is_active().then(|| picker.rows());
            draw_ui(
                &mut terminal,
                &s,
                instance,
                show_help,
                overlay.as_deref(),
                picker_rows,
                &ui_entries,
            )?;
        }

        if !event::poll(Duration::from_millis(50))? {
            continue;
        }
        let ev = event::read()?;

        if let Event::Mouse(m) = ev {
            if picker.is_active() || ex.is_active() {
                continue;
            }
            match m.kind {
                MouseEventKind::ScrollUp | MouseEventKind::ScrollDown => {
                    let steps: f32 = if m.kind == MouseEventKind::ScrollUp {
                        0.01
                    } else {
                        -0.01
                    };
                    use crate::undo::ParamUndo;
                    let mut s = shared.lock().unwrap();
                    let slot = s.selected;
                    let r = ROWS[slot.min(ROWS.len() - 1)];
                    if src_index(r).is_none() {
                        continue;
                    }
                    let old = s.get_param(slot);
                    let v = s.get(r) + steps;
                    s.set(r, v);
                    let new = s.get_param(slot);
                    if let (Some(old), Some(new)) = (old, new) {
                        history.record(slot, "Adjust", old, new);
                    }
                }
                MouseEventKind::Down(_) => {
                    let row = (m.row as usize).saturating_sub(3);
                    if row < ROWS.len() {
                        shared.lock().unwrap().selected = row;
                    }
                }
                _ => {}
            }
            continue;
        }
        let Event::Key(key) = ev else { continue };
        ex_msg = None;

        if picker.is_active() {
            if let crate::picker::PickerEvent::Chosen(addr) = picker.handle_key(key.code) {
                use crate::undo::{ParamUndo, ParamValue};
                let mut s = shared.lock().unwrap();
                let r = ROWS[s.selected.min(ROWS.len() - 1)];
                if let Some(slot) = binding_slot(r) {
                    let old = s.get_param(slot);
                    let text = addr.as_ref().map(|a| a.to_string());
                    if let Some(k) = src_index(r) {
                        s.srcs[k] = addr.clone();
                        s.resolved[k] = None;
                    }
                    if let Some(old) = old {
                        history.record(slot, "Bind", old, ParamValue::Src(text));
                    }
                }
            }
            continue;
        }
        if ex.is_active() {
            let completer =
                crate::excmd::standard_completer(crate::excmd::patch_names(&state::patches_dir()));
            if let crate::excmd::ExEvent::Submit(cmd) = ex.handle_key(key.code, &completer) {
                use crate::excmd::ExCommand;
                let params = snapshot_params(&shared.lock().unwrap());
                match cmd {
                    ExCommand::Write(name) => {
                        ex_msg = Some(
                            match crate::excmd::ex_write(
                                name,
                                &mut patch_name,
                                &mut baseline,
                                &params,
                            ) {
                                Ok(m) | Err(m) => m,
                            },
                        );
                    }
                    ExCommand::Edit(name) => match state::load_patch::<state::GridsParams>(&name) {
                        Ok(p) => {
                            apply_params(&mut shared.lock().unwrap(), &p);
                            baseline = state::to_toml_string(&snapshot_params(
                                &shared.lock().unwrap(),
                            ))
                            .unwrap_or_default();
                            patch_name = Some(name.clone());
                            ex_msg = Some(format!("Loaded {}", name));
                        }
                        Err(e) => ex_msg = Some(e.to_string()),
                    },
                    ExCommand::Quit { force } => {
                        if !force && crate::excmd::is_dirty(&params, &baseline) {
                            ex_msg = Some(String::from(
                                "Unsaved changes (:q! to discard, :w <name> to save)",
                            ));
                        } else {
                            should_quit = true;
                        }
                    }
                    ExCommand::WriteQuit(name) => {
                        match crate::excmd::ex_write(name, &mut patch_name, &mut baseline, &params)
                        {
                            Ok(_) => should_quit = true,
                            Err(m) => ex_msg = Some(m),
                        }
                    }
                    ExCommand::Set(k, v) => {
                        let mut s = shared.lock().unwrap();
                        ex_msg = Some(ex_set(&mut s, &mut history, &k, &v));
                    }
                    ExCommand::Unknown(c) => ex_msg = Some(format!("Not a command: {}", c)),
                }
            }
            if should_quit {
                break;
            }
            continue;
        }

        if !matches!(key.code, KeyCode::Char('g')) {
            pending_g = false;
        }
        if key.code == KeyCode::Char('r') && key.modifiers == KeyModifiers::CONTROL {
            let n = count.take();
            let mut s = shared.lock().unwrap();
            ex_msg = Some(crate::undo::history_status("Redo", n, || {
                history.redo(&mut *s)
            }));
            continue;
        }
        if key.code == KeyCode::Char('s') && key.modifiers == KeyModifiers::CONTROL {
            let params = snapshot_params(&shared.lock().unwrap());
            let _ = state::save_module_state("grids", instance, &params);
            ex_msg = Some(String::from("Saved"));
            continue;
        }

        match key.code {
            KeyCode::Char(c) if c.is_ascii_digit() && count.push(c) => {}
            KeyCode::Char('j') | KeyCode::Down => {
                let n = count.take() as i32;
                let mut s = shared.lock().unwrap();
                s.selected = crate::keys::cycle(s.selected, n, ROWS.len());
            }
            KeyCode::Char('k') | KeyCode::Up => {
                let n = count.take() as i32;
                let mut s = shared.lock().unwrap();
                s.selected = crate::keys::cycle(s.selected, -n, ROWS.len());
            }
            KeyCode::Char(c @ ('h' | 'l' | 'H' | 'L')) => {
                let n = count.take() as i32;
                let (steps, coarse) = match c {
                    'h' => (-n, false),
                    'l' => (n, false),
                    'H' => (-n, true),
                    _ => (n, true),
                };
                use crate::keys::step_f32;
                use crate::undo::ParamUndo;
                let mut s = shared.lock().unwrap();
                let slot = s.selected;
                let r = ROWS[slot.min(ROWS.len() - 1)];
                let old = s.get_param(slot);
                if r == Row::Mode {
                    s.drums_mode = !s.drums_mode;
                } else {
                    let v = step_f32(s.get(r), steps, 0.01, coarse, 0.0, 1.0);
                    s.set(r, v);
                }
                let new = s.get_param(slot);
                if let (Some(old), Some(new)) = (old, new) {
                    history.record(slot, "Adjust", old, new);
                }
            }
            KeyCode::Char('0') => {
                count.clear();
                use crate::undo::ParamUndo;
                let mut s = shared.lock().unwrap();
                let slot = s.selected;
                let old = s.get_param(slot);
                let def = GridsState::new();
                if let Some(v) = def.get_param(slot) {
                    s.set_param(slot, v.clone());
                    if let Some(old) = old {
                        history.record(slot, "Reset", old, v);
                    }
                }
            }
            KeyCode::Char('@') => {
                count.clear();
                let s = shared.lock().unwrap();
                let r = ROWS[s.selected.min(ROWS.len() - 1)];
                if binding_slot(r).is_some() {
                    let current = src_index(r).and_then(|k| s.srcs[k].clone());
                    drop(s);
                    let sources = Manifest::open()
                        .map(|m| routing::live_sources(&m.entries()))
                        .unwrap_or_default();
                    picker.open(sources, current.as_ref());
                } else {
                    ex_msg = Some(format!("{} is not bindable", row_label(r)));
                }
            }
            KeyCode::Char('x') => {
                count.clear();
                use crate::undo::{ParamUndo, ParamValue};
                let mut s = shared.lock().unwrap();
                let r = ROWS[s.selected.min(ROWS.len() - 1)];
                if let Some(slot) = binding_slot(r) {
                    if let Some(k) = src_index(r) {
                        if s.srcs[k].is_some() {
                            let old = s.get_param(slot);
                            s.srcs[k] = None;
                            s.resolved[k] = None;
                            if let Some(old) = old {
                                history.record(slot, "Unbind", old, ParamValue::Src(None));
                            }
                        }
                    }
                }
            }
            KeyCode::Char('u') => {
                let n = count.take();
                let mut s = shared.lock().unwrap();
                ex_msg = Some(crate::undo::history_status("Undo", n, || {
                    history.undo(&mut *s)
                }));
            }
            KeyCode::Char('g') => {
                count.clear();
                if pending_g {
                    pending_g = false;
                    shared.lock().unwrap().selected = 0;
                } else {
                    pending_g = true;
                }
            }
            KeyCode::Char('G') => {
                count.clear();
                shared.lock().unwrap().selected = ROWS.len() - 1;
            }
            KeyCode::Char(' ') => {
                if transport_ui.is_none() {
                    transport_ui = ShmTransport::open().ok();
                }
                if let Some(ref mut t) = transport_ui {
                    t.toggle_playing();
                }
            }
            KeyCode::Char(':') => {
                count.clear();
                ex.open();
            }
            KeyCode::Char('?') => {
                count.clear();
                show_help = !show_help;
            }
            _ => {
                count.clear();
            }
        }
        if should_quit {
            break;
        }
    }

    crossterm::terminal::disable_raw_mode()?;
    execute!(io::stdout(), crossterm::terminal::LeaveAlternateScreen)?;
    Ok(())
}

fn ex_set(
    s: &mut GridsState,
    history: &mut crate::undo::ParamHistory,
    key: &str,
    value: &str,
) -> String {
    use crate::undo::ParamUndo;
    use crate::undo::ParamValue as V;
    if key == "mode" {
        s.drums_mode = value != "euclid";
        return format!("mode = {}", if s.drums_mode { "drums" } else { "euclid" });
    }
    let row = match key {
        "x" => Row::X,
        "y" => Row::Y,
        "chaos" => Row::Chaos,
        "fill1" => Row::Fill1,
        "fill2" => Row::Fill2,
        "fill3" => Row::Fill3,
        "len1" => Row::Len1,
        "len2" => Row::Len2,
        "len3" => Row::Len3,
        _ => return format!("Unknown setting: {key}"),
    };
    match value.parse::<f32>() {
        Ok(v) => {
            s.set(row, v);
            format!("{key} = {}", row_text(s, row))
        }
        Err(_) => {
            let Some(k) = src_index(row) else {
                return format!("{key}: not bindable");
            };
            let v = if value == "-" {
                V::Src(None)
            } else {
                if SourceAddr::parse(value).is_none() {
                    return format!("{key}: not a number or source: {value}");
                }
                V::Src(Some(value.to_string()))
            };
            let bind_slot = SRC_SLOT_BASE + k;
            let old = s.get_param(bind_slot);
            s.set_param(bind_slot, v.clone());
            if let Some(old) = old {
                history.record(bind_slot, "Set", old, v);
            }
            format!("{key} cable updated")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn node_data_extracted_in_full() {
        assert_eq!(NODES.len(), 25 * 96, "25 nodes x 3 parts x 32 steps");
        // node 8 (the classic house corner) has a kick on step 0
        assert!(node_byte(8, 0, 0) > 200, "{}", node_byte(8, 0, 0));
    }

    #[test]
    fn drum_map_interpolates_continuously() {
        // moving x a little moves the level a little
        let a = read_drum_map(0, 0, 100, 100) as i32;
        let b = read_drum_map(0, 0, 104, 100) as i32;
        assert!((a - b).abs() < 64, "smooth in x: {a} vs {b}");
    }

    #[test]
    fn density_threshold_gates_triggers() {
        let mut core = PatternCore::new(0x1);
        core.density = [255; 3];
        let full: usize = (0..32).map(|s| core.step(s).fired.iter().filter(|f| **f).count()).sum();
        let mut core = PatternCore::new(0x1);
        core.density = [0; 3];
        let empty: usize = (0..32).map(|s| core.step(s).fired.iter().filter(|f| **f).count()).sum();
        assert!(full > 24, "full density fires a lot: {full}");
        assert!(empty < 6, "zero density barely fires: {empty}");
    }

    #[test]
    fn euclidean_table_matches_known_patterns() {
        let t = build_euclidean();
        // length 4, full density -> all four steps
        let mask = t[(4 - 1) * 32 + 31];
        assert_eq!(mask & 0xf, 0xf, "4/4: {mask:b}");
        // length 8, half density -> 4 evenly spaced hits
        let mask = t[(8 - 1) * 32 + 16];
        assert_eq!(mask.count_ones(), 4, "{mask:b}");
        let m = mask & 0xff;
        assert!(m == 0b0101_0101 || m == 0b1010_1010, "even spread: {m:b}");
    }

    #[test]
    fn euclid_mode_cycles_and_resets() {
        let mut core = PatternCore::new(0x2);
        core.drums_mode = false;
        core.euclidean_length = [63; 3]; // (63>>3)+1 = 8 steps
        core.density = [255; 3];
        let mut fired = 0;
        for s in 0..32 {
            if core.step(s).fired[0] {
                fired += 1;
            }
        }
        // full density 8-step euclid over 16 sixteenths = 16 hits...
        // (refreshes every other 32nd step)
        assert!(fired >= 8, "euclid fires through the cycle: {fired}");
    }

    #[test]
    fn params_round_trip_through_toml() {
        let mut s = GridsState::new();
        s.x = 0.7;
        s.drums_mode = false;
        s.fill[2] = 0.9;
        s.srcs[0] = SourceAddr::parse("lfo/0/s1");
        let toml = state::to_toml_string(&snapshot_params(&s)).expect("serializes");
        let back: state::GridsParams = toml::from_str(&toml).expect("parses");
        let mut s2 = GridsState::new();
        apply_params(&mut s2, &back);
        assert!((s2.x - 0.7).abs() < 1e-6);
        assert!(!s2.drums_mode);
        assert!((s2.fill[2] - 0.9).abs() < 1e-6);
        assert!(s2.srcs[0].is_some());
    }

    #[test]
    fn every_value_row_is_bindable() {
        use crate::undo::ParamUndo;
        use crate::undo::ParamValue as V;
        for r in ROWS {
            if r == Row::Mode {
                continue;
            }
            let i = src_index(r).unwrap_or_else(|| panic!("{r:?} must be bindable"));
            let mut s = GridsState::new();
            s.set_param(SRC_SLOT_BASE + i, V::Src(Some("lfo/0/a1".into())));
            assert!(s.srcs[i].is_some(), "{r:?} binds");
        }
    }
}
