pub mod badge;
pub mod conductor;
pub mod envelope;
pub mod excmd;
pub mod keys;
pub mod layout;
pub mod mixer;
pub mod picker;
pub mod routing;
pub mod scope;
pub mod sequencer;
pub mod shm;
pub mod state;
pub mod theme;
pub mod tmux;
pub mod tone;
pub mod undo;
pub mod voice;

pub const NUM_TRACKS: usize = 8;
